
spring.application.name=event-gateway

server.port=8080

spring.h2.console.enabled=true

spring.datasource.url=jdbc:h2:mem:eventdb

spring.datasource.driverClassName=org.h2.Driver

spring.datasource.username=sa

spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

resilience4j.retry.instances.accountService.max-attempts=3
resilience4j.retry.instances.accountService.wait-duration=2s